/* ============================================================
   sw.js — offline support
   ------------------------------------------------------------
   GENERATED by tools/build-sw.js. Do not edit by hand; run
   `node tools/build-sw.js` after changing any asset.

   The course never touches the network, so everything is
   precached on install and served cache-first afterwards. Once
   the install completes the app works with no connection at all.

   The cache name embeds a hash of every asset's contents, so a
   changed file produces a new cache and the old one is deleted
   on activate.
   ============================================================ */

const CACHE = 'francais-761779b122';

/* index.html is the only shell entry. Caching './' as well stored a
   second copy of the same page, and the stale one won. */
const ASSETS = [
  'css/base.css',
  'css/components.css',
  'css/tokens.css',
  'data/curriculum.js',
  'data/en/literals.js',
  'data/en/s01-06.js',
  'data/en/s07-12.js',
  'data/en/s13-18.js',
  'data/en/s19-24.js',
  'data/en/s25-30.js',
  'data/en/s31-33.js',
  'data/grammar.js',
  'data/sections/s01.js',
  'data/sections/s02.js',
  'data/sections/s03.js',
  'data/sections/s04.js',
  'data/sections/s05.js',
  'data/sections/s06.js',
  'data/sections/s07.js',
  'data/sections/s08.js',
  'data/sections/s09.js',
  'data/sections/s10.js',
  'data/sections/s11.js',
  'data/sections/s12.js',
  'data/sections/s13.js',
  'data/sections/s14.js',
  'data/sections/s15.js',
  'data/sections/s16.js',
  'data/sections/s17.js',
  'data/sections/s18.js',
  'data/sections/s19.js',
  'data/sections/s20.js',
  'data/sections/s21.js',
  'data/sections/s22.js',
  'data/sections/s23.js',
  'data/sections/s24.js',
  'data/sections/s25.js',
  'data/sections/s26.js',
  'data/sections/s27.js',
  'data/sections/s28.js',
  'data/sections/s29.js',
  'data/sections/s30.js',
  'data/sections/s31.js',
  'data/sections/s32.js',
  'data/sections/s33.js',
  'icons/icon-180.png',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'index.html',
  'js/app.js',
  'js/audio.js',
  'js/grammar.js',
  'js/i18n.js',
  'js/lexicon.js',
  'js/offline.js',
  'js/phonemes.js',
  'js/phonetics.js',
  'js/render.js',
  'js/store.js',
  'manifest.webmanifest'
];

/* cache.add() performs an ordinary fetch, which the browser is free to
   satisfy from its own HTTP cache. That silently stored a stale copy of the
   shell here. Forcing cache: 'reload' makes every precache entry come from
   the network. */
function fetchFresh(url) {
  let req;
  try {
    req = new Request(url, { cache: 'reload' });
  } catch (e) {
    req = url;                    /* very old browsers ignore the init */
  }
  return fetch(req);
}

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      /* One rejection would abort the whole batch and leave the app with no
         offline copy at all, so each entry succeeds or fails alone. */
      .then(cache => Promise.all(
        ASSETS.map(url =>
          fetchFresh(url)
            .then(res => {
              if (!res || !res.ok) throw new Error('HTTP ' + (res && res.status));
              return cache.put(url, res);
            })
            .catch(err => { console.warn('[sw] could not cache', url, err); })
        )
      ))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(names => Promise.all(
        names.filter(n => n.startsWith('francais-') && n !== CACHE)
             .map(n => caches.delete(n))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  /* A navigation to any in-app URL resolves to the one page we have. */
  if (req.mode === 'navigate') {
    event.respondWith(
      caches.match('index.html', { ignoreSearch: true })
        .then(hit => hit || fetch(req))
    );
    return;
  }

  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then(hit => {
      if (hit) return hit;
      /* Not precached — fetch it and keep a copy for next time. */
      return fetch(req).then(res => {
        if (res && res.ok && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
        }
        return res;
      }).catch(() => caches.match('index.html', { ignoreSearch: true }));
    })
  );
});

/* Lets the page report what is cached. */
self.addEventListener('message', event => {
  if (event.data === 'version' && event.source) {
    event.source.postMessage({ type: 'version', cache: CACHE, assets: ASSETS.length });
  }
});
