/* Generates sw.js with an accurate precache list.
   Hand-maintaining that list guarantees it goes stale, so it is built from
   what is actually on disk, and the cache name carries a hash of those file
   contents. Change any file and the hash changes, which is what makes the
   service worker fetch the new version instead of serving the old one. */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const INCLUDE_DIRS = ['css', 'js', 'data', 'icons'];
const INCLUDE_FILES = ['index.html', 'manifest.webmanifest'];
const SKIP = new Set(['sw.js']);

function walk(dir, acc = []) {
  for (const name of fs.readdirSync(path.join(ROOT, dir)).sort()) {
    const rel = path.posix.join(dir, name);
    const stat = fs.statSync(path.join(ROOT, rel));
    if (stat.isDirectory()) walk(rel, acc);
    else if (!SKIP.has(name)) acc.push(rel);
  }
  return acc;
}

let assets = [];
for (const d of INCLUDE_DIRS) {
  if (fs.existsSync(path.join(ROOT, d))) assets = assets.concat(walk(d));
}
for (const f of INCLUDE_FILES) {
  if (fs.existsSync(path.join(ROOT, f))) assets.push(f);
}
assets.sort();

/* Bump when the service worker's own logic changes, so an existing
   install does not keep reusing a cache built by the old rules. */
const LOGIC_VERSION = 2;

const hash = crypto.createHash('sha1');
hash.update('logic:' + LOGIC_VERSION);
for (const a of assets) hash.update(a).update(fs.readFileSync(path.join(ROOT, a)));
const version = hash.digest('hex').slice(0, 10);

const bytes = assets.reduce((n, a) => n + fs.statSync(path.join(ROOT, a)).size, 0);

const sw = `/* ============================================================
   sw.js — offline support
   ------------------------------------------------------------
   GENERATED by tools/build-sw.js. Do not edit by hand; run
   \`node tools/build-sw.js\` after changing any asset.

   The course never touches the network, so everything is
   precached on install and served cache-first afterwards. Once
   the install completes the app works with no connection at all.

   The cache name embeds a hash of every asset's contents, so a
   changed file produces a new cache and the old one is deleted
   on activate.
   ============================================================ */

const CACHE = 'francais-${version}';

/* index.html is the only shell entry. Caching './' as well stored a
   second copy of the same page, and the stale one won. */
const ASSETS = [
${assets.map(a => `  '${a}'`).join(',\n')}
];

/* cache.add() performs an ordinary fetch, which the browser is free to
   satisfy from its own HTTP cache. That silently stored a stale copy of the
   shell here. Forcing cache: 'reload' makes every precache entry come from
   the network. */
function fetchFresh(url) {
  let req;
  try {
    req = new Request(url, { cache: 'reload' });
  } catch (e) {
    req = url;                    /* very old browsers ignore the init */
  }
  return fetch(req);
}

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      /* One rejection would abort the whole batch and leave the app with no
         offline copy at all, so each entry succeeds or fails alone. */
      .then(cache => Promise.all(
        ASSETS.map(url =>
          fetchFresh(url)
            .then(res => {
              if (!res || !res.ok) throw new Error('HTTP ' + (res && res.status));
              return cache.put(url, res);
            })
            .catch(err => { console.warn('[sw] could not cache', url, err); })
        )
      ))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(names => Promise.all(
        names.filter(n => n.startsWith('francais-') && n !== CACHE)
             .map(n => caches.delete(n))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  /* A navigation to any in-app URL resolves to the one page we have. */
  if (req.mode === 'navigate') {
    event.respondWith(
      caches.match('index.html', { ignoreSearch: true })
        .then(hit => hit || fetch(req))
    );
    return;
  }

  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then(hit => {
      if (hit) return hit;
      /* Not precached — fetch it and keep a copy for next time. */
      return fetch(req).then(res => {
        if (res && res.ok && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy));
        }
        return res;
      }).catch(() => caches.match('index.html', { ignoreSearch: true }));
    })
  );
});

/* Lets the page report what is cached. */
self.addEventListener('message', event => {
  if (event.data === 'version' && event.source) {
    event.source.postMessage({ type: 'version', cache: CACHE, assets: ASSETS.length });
  }
});
`;

fs.writeFileSync(path.join(ROOT, 'sw.js'), sw);
console.log('sw.js written');
console.log('  assets  :', assets.length);
console.log('  size    :', (bytes / 1024).toFixed(0) + ' KB');
console.log('  version :', version);
